modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
   modId="magicmod"
   version="${file.jarVersion}"
   displayName="Magic Mod"
   description='''
   Cool magic mod.
   '''
[[dependencies.magicmod]]
   modId="forge"
   mandatory=true
   versionRange="[47,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.magicmod]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20.1,1.21)"
   ordering="NONE"
   side="BOTH"
